export enum ENUM_TEMPLATE_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5200,
    NOT_ACCESS_ERROR = 5201,
}

export enum ENUM_TEMPLATE_QUESTION_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5300,
    NOT_ACCESS_ERROR = 5301,
}

export enum ENUM_TEMPLATE_FORM_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5400,
    NOT_ACCESS_ERROR = 5401,
}
