export enum ENUM_TEMPLATE_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5200,
    FORBIDDEN_ERROR = 5201,
    NOT_FOUND_SHARED_USERS_ERROR = 5202,
}

export enum ENUM_TEMPLATE_QUESTION_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5300,
    FORBIDDEN_ERROR = 5301,
}

export enum ENUM_TEMPLATE_FORM_STATUS_CODE_ERROR {
    NOT_FOUND_ERROR = 5400,
    FORBIDDEN_ERROR = 5401,
}
