name: Project Task
description: Create a new project task
title: ""
labels: [ "project-task" ]
assignees:
  - G

body:
  - type: input
    id: title
    attributes:
      label: Task Title
      description: Brief title of the task
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What needs to be done
      description: Functionality description
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
