name: Project Task
description: Create a new project task
title: "[FB-]: "
labels: [ "project-task" ]
assignees:
  - G

body:
  - type: markdown
    attributes:
      value: |
        Creating a new project task

  - type: input
    id: title
    attributes:
      label: Task Title
      description: Brief description of what needs to be done
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Describe requirements and expected outcome
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How to verify the task is completed correctly?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional information
    validations:
      required: false