import { ENUM_ELASTICSEARCH_ORDER_DIRECTION_TYPE } from './elasticsearch.enum.constant';

export const ELASTICSEARCH_DEFAULT_PER_PAGE = 20;
export const ELASTICSEARCH_DEFAULT_MAX_PER_PAGE = 100;

export const ELASTICSEARCH_DEFAULT_PAGE = 1;
export const ELASTICSEARCH_DEFAULT_MAX_PAGE = 20;

export const ELASTICSEARCH_DEFAULT_ORDER_BY = 'createdAt';
export const ELASTICSEARCH_DEFAULT_ORDER_DIRECTION: ENUM_ELASTICSEARCH_ORDER_DIRECTION_TYPE =
    ENUM_ELASTICSEARCH_ORDER_DIRECTION_TYPE.ASC;

export const ELASTICSEARCH_DEFAULT_AVAILABLE_ORDER_BY: string[] = ['createdAt'];
export const ELASTICSEARCH_DEFAULT_AVAILABLE_ORDER_DIRECTION: ENUM_ELASTICSEARCH_ORDER_DIRECTION_TYPE[] =
    Object.values(ENUM_ELASTICSEARCH_ORDER_DIRECTION_TYPE);
