name: Update Issue Title
on:
  issues:
    types: [ opened ]

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const newTitle = `[FB-#${issue.number}]:${issue.title.split(':').pop().trim()}`;
            
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              title: newTitle
            });